apiVersion: apps/v1
kind: Deployment
metadata:
  name: department
  labels:
    app: department
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department
  template:
    metadata:
      labels:
        app: department
    spec:
      containers:
      - name: department
        image: 992382462614.dkr.ecr.us-west-2.amazonaws.com
        ports:
        - containerPort: 5001
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: department-service
spec:
  selector:
    app: department
  type: NodePort
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
